const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const b=await chromium.launch({headless:true});const ctx=await b.newContext({viewport:{width:1440,height:1100}});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:8765/tabkhat-al-yawm/';await p.goto(url);await p.waitForFunction(()=>document.querySelectorAll('.card').length===44);await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await p.waitForFunction(()=>!!navigator.serviceWorker.controller);let checks=0;const check=(a,msg)=>{assert(a,msg);checks++};check(await p.locator('.card').count()===44,'all recipes');
for(let id=0;id<44;id++){await p.evaluate(id=>openRecipe(id),id);check(await p.locator('#detailTitle').textContent()===await p.evaluate(id=>recipes[id].name,id),'recipe title');check(await p.locator('.ingredient').count()>0,'ingredients');if(id<36){await p.waitForFunction(()=>document.querySelector('.detail-image').complete);check(await p.locator('.detail-image').evaluate(x=>x.naturalWidth>0),'recipe image '+id)}await p.locator('#detailDialog [data-close]').click()}
await p.screenshot({path:'desktop.png',fullPage:true});
await p.locator('[data-favorite="0"]').click();await p.reload();check(await p.locator('[data-favorite="0"]').getAttribute('aria-pressed')==='true','favorite persisted');
await p.locator('#q').fill('جميد');check(await p.locator('.card').count()===1,'ingredient search');await p.locator('[data-action="reset"]').first().click();
for(const cat of ['الحلويات','السلطات','السندويشات','الشوربة','المعجنات','المعكرونة','المقبلات','بيتزا','أكلات خفيفة']){await p.locator('#categories').getByRole('button',{name:cat,exact:false}).click();check(await p.locator('.card').count()>0,'category populated '+cat)}await p.locator('[data-action="reset"]').first().click();
await p.evaluate(()=>openRecipe(0));await p.locator('#servings').fill('12');await p.locator('#servings').dispatchEvent('change');check((await p.locator('#ingredients').textContent()).match(/[2٢] كغ لحم/),'double portions');await p.locator('[data-action="addAll"]').click();await p.locator('[data-action="addAll"]').click();check(await p.evaluate(()=>cart[0].qty)===4,'cart sums');await p.locator('#servings').fill('0');await p.locator('#servings').dispatchEvent('change');check(await p.locator('#servings').inputValue()==='12','invalid portion rejected');
await p.locator('[data-action="cook"]').click();check(await p.locator('.cook-step').count()===1,'cook mode');await p.locator('[data-action="nextStep"]').click();check((await p.locator('#toolBody').textContent()).includes('الخطوة 2'),'cook next');await p.locator('#toolDialog [data-action="timer"]').click();await p.locator('[data-action="startTimer"]').click();check(await p.evaluate(()=>timerEnd>Date.now()),'timer started');await p.locator('[data-action="backCook"]').click();check((await p.locator('#toolBody').textContent()).includes('الخطوة 2'),'timer preserves step');await p.locator('#toolDialog [data-close]').click();await p.locator('#detailDialog [data-close]').click();
await p.evaluate(()=>planner());await p.locator('#day-0').selectOption('0');await p.locator('[data-plan-servings="0"]').fill('8');await p.locator('[data-plan-servings="0"]').dispatchEvent('change');await p.reload();check(await p.evaluate(()=>plan[0].servings)===8,'plan persists');
await p.evaluate(()=>pantry());await p.locator('#pantryInput').fill('دجاج، أرز');await p.locator('#pantryForm button').click();check(await p.locator('#pantryResults .mini-result').count()>0,'pantry results');await p.locator('#toolDialog [data-close]').click();
await p.evaluate(()=>helper());await p.locator('#helperInput').fill('ما عاصمة فرنسا');await p.locator('#helperForm button').click();check((await p.locator('#helperOutput').textContent()).includes('أساعد فقط'),'helper scope');await p.locator('#helperInput').fill('بديل الكريمة');await p.locator('#helperForm button').click();check((await p.locator('#helperOutput').textContent()).includes('النشا'),'substitution');await p.locator('#toolDialog [data-close]').click();
await p.evaluate(()=>openRecipe(0));await p.locator('[data-action="saveOffline"]').click();await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('تم حفظ الوصفة'));await p.locator('#detailDialog [data-close]').click();await ctx.setOffline(true);await p.reload();await p.waitForFunction(()=>document.querySelectorAll('.card').length===44);await p.evaluate(()=>openRecipe(0));await p.waitForFunction(()=>document.querySelector('.detail-image').complete);check(await p.locator('.detail-image').evaluate(x=>x.naturalWidth>0),'offline saved image');check(await p.locator('.ingredient').count()>0,'offline recipe');await ctx.setOffline(false);await p.locator('#detailDialog [data-close]').click();
for(const width of [390,320,768]){await p.setViewportSize({width,height:844});await p.evaluate(()=>scrollTo(0,0));check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no overflow '+width);if(width===390)await p.screenshot({path:'mobile.png',fullPage:true});await p.evaluate(()=>planner());check(await p.locator('#toolDialog').evaluate(el=>el.scrollWidth<=el.clientWidth),'planner fits '+width);await p.locator('#toolDialog [data-close]').click()}
await p.evaluate(()=>{localStorage.setItem('tabkhatFav','broken');localStorage.setItem('tabkhatCartV6','broken');localStorage.setItem('tabkhatPlanV6','broken')});await p.reload();check(await p.locator('.card').count()===44,'corrupt storage recovered');
check(errors.length===0,'no runtime errors '+errors.join(','));console.log(JSON.stringify({checks,errors},null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
